sudo: true
dist: trusty
services:
  - docker

cache: 
  apt: true
  ccache: true
  packages: true
  directories:
    - $HOME/.ccache
    - $HOME/.m2

language: r

env:
  global:
    - STAN_BRANCH=master
    - STAN_MATH_BRANCH=master

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - COMPILER=g++-7
       
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew install gcc6 && CC=gcc-6 && CXX=g++-6"

before_install:
  - eval "${MATRIX_EVAL}"
  - echo -e "#\x21/bin/sh\n\$1 &\nPROCESS=\"\$!\"\nwhile :\ndo\n  RESULT=\`ps -p \${PROCESS} -o comm=\`" > wait4.sh
  - echo -e "  if [ -z \"\${RESULT}\" ]; then\n    wait \${PROCESS}; exit \$?\n  else\n    echo \"-\"; sleep 10\n  fi\ndone\nexit \$?" >> wait4.sh
  - more wait4.sh
  - echo -e "Package\x3A mnb_bnm" > DESCRIPTION
  - chmod 755 wait4.sh

before_script: 
  - Rscript -e "install.packages(c('inline', 'Rcpp', 'coda', 'BH', 'RcppEigen', 'RInside', 'RUnit', 'ggplot2', 'gridExtra', 'knitr', 'rmarkdown'), repos='http://cran.rstudio.com')"
  - git config -f .gitmodules submodule.stan.branch ${STAN_BRANCH} 
  - git config -f .gitmodules submodule.StanHeaders/inst/include/mathlib.branch ${STAN_MATH_BRANCH}
  - git submodule update --remote
  - R CMD build StanHeaders/
  - R CMD INSTALL `find StanHeaders*.tar.gz`
  - if [[ $TRAVIS_OS_NAME = 'osx' ]] ; then sudo tlmgr update --self; fi
  - if [[ $TRAVIS_OS_NAME = 'osx' ]] ; then sudo tlmgr install verbatimbox readarray ifnextok multirow fancyvrb url titlesec booktabs; fi 
  - if [[ $TRAVIS_OS_NAME != 'osx' ]] ; then tlmgr install verbatimbox readarray ifnextok; fi
  - if [[ $TRAVIS_OS_NAME = "osx" ]] ; then  brew install ccache; brew link ccache; fi
  - echo "CXX = $CXX" >> ./rstan/R_Makevars 
  - echo "CXX14 = $CXX" >> ./rstan/R_Makevars 
  - echo "CXX14FLAGS = `R CMD config CXXFLAGS` -pedantic -g0" >> ./rstan/R_Makevars 
  - export CLANG_EXTRA_ARG=""
  - if [[ $CXX =~ clang.* ]] ;  then export CLANG_EXTRA_ARG=" -Qunused-arguments -fcolor-diagnostics " ; fi
  - echo ${CXX} --version
  - echo ${CLANG_EXTRA_ARG}
  - more ./rstan/R_Makevars
  - mkdir -p ~/.R/; cat ./rstan/R_Makevars > ~/.R/Makevars
  - more ~/.R/Makevars

notifications:
  email:
    # recipients:
      # - stan-buildbot@googlegroups.com
    on_success: change
    on_failure: always

script:
  - cd rstan 
  - R -q -e "library(Rcpp); sessionInfo()"
  - ../wait4.sh "make install" && cd tests && R -q -f runRunitTests.R
